### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by melihnasli** [CankayaUniversity/ceng-407-408-2023-2024-Indoor-Location-Classification-System#1]
Create the Test Plan Page and Preapare Template. Fill in the test plan sections.

**Comment by xsserdemir** [comment]
I created the Test Plan page and template. ButI will fill the sections later.

**Comment by xsserdemir** [comment]
I filled in the test plan sections and created a template. I forwarded it to Ata to fill in the remaining parts.
